name: lab2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf

    
